# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17gBGZGC8Y2Hxu1qaVzDZJ1zCyHeQmyhb
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2 * np.pi, 500)
y = np.sin(x)

plt.figure(figsize=(8, 5))
plt.plot(x, y, label='sin(x)', color='blue', linewidth=2)
plt.title("Sinus Funktsiyasi Grafigi")
plt.xlabel("x (rad)")
plt.ylabel("sin(x)")
plt.axhline(0, color='black', linewidth=0.5, linestyle='--')
plt.axvline(0, color='black', linewidth=0.5, linestyle='--')
plt.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.7)
plt.legend()
plt.show()

np.random.seed(42)
x = np.random.rand(100)
y = np.random.rand(100)

plt.figure(figsize=(8, 5))
plt.scatter(x, y, color='purple', alpha=0.7, edgecolor='black')
plt.title("Tasodifiy Nuqtalar (Scatter Graf)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.7)
plt.show()

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('rasm1.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('rasm2.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('rasm3.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

import pandas as pd

data = pd.read_csv("WHO COVID-19 cases.csv")

print("Ma'lumotlarning birinchi 5 qatori:")
print(data.head())

cases_by_country = data.groupby("Country").sum()["Cumulative_cases"]

print("\nHar bir davlat bo'yicha umumiy COVID-19 holatlari:")
print(cases_by_country)

country_filter = "Uzbekistan"
uzbekistan_data = data[data["Country"] == country_filter]

print(f"\n{country_filter} uchun ma'lumotlar:")
print(uzbekistan_data)

import matplotlib.pyplot as plt

top_10_countries = cases_by_country.sort_values(ascending=False).head(10)

plt.figure(figsize=(10, 6))
top_10_countries.plot(kind="bar", color="skyblue")
plt.title("Eng ko'p COVID-19 holatlari aniqlangan davlatlar", fontsize=16)
plt.xlabel("Davlat", fontsize=12)
plt.ylabel("Cumulative Cases", fontsize=12)
plt.xticks(rotation=45)
plt.show()